swagger: "2.0"
info:
  version: "0.0.1"
  title: Browse people list from irit.fr
host: localhost:10010
basePath: /v1
schemes:
  - http
  - https
consumes: [application/json]
produces: [application/json]
paths:
  /vms:
    x-swagger-router-controller: vms
    get:
      description: Returns the list of VM hostnames the user can access
      operationId: vms
    responses:
      "200":
        description: Success
        schema:
          type: array
          items:
            type: string
  /vm:
    x-swagger-router-controller: vm
    get:
      description: Returns information for a VM using its hostname
      parameters:
        - name: hostname
          in: path
          description: Hostname of the VM
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Vm"
        "400":
          description: Bad request
          schema:
            $ref: "#/definitions/VmError"

definitions:
  Vm:
    required:
      - interfaces
      - credentials
      - dns
    properties:
      interfaces:
        type: array
        items:
          
      number: { type: string }
      location: { type: string }
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  VmError:
